<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="userInfo.aspx.cs" Inherits="SMIS.Manager.userInfo" %>


<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div style="height: 50px; width: 90%">
        <h3>>>>旅客信息</h3>
    </div>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderStyle="Solid" CellPadding="20"
        CssClass="table-bordered" DataSourceID="SqlDataSource2" Font-Size="Large" Height="50px" HorizontalAlign="Center" Width="90%"
        DataKeyNames="ID" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True">
        <AlternatingRowStyle BackColor="White" />
        <HeaderStyle BackColor="White" />
        <Columns>
            <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" ReadOnly="True" />
            <asp:BoundField DataField="姓名" HeaderText="姓名" SortExpression="姓名" />
            <asp:BoundField DataField="用户名" HeaderText="用户名" SortExpression="用户名" />
            <asp:BoundField DataField="手机号" HeaderText="手机号" SortExpression="手机号" />
            <asp:BoundField DataField="余额" HeaderText="余额" SortExpression="余额" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:airDBConnectionString %>"
        SelectCommand="SELECT [uid] ID, [uname] 姓名, [uloginname] 用户名, [utel] 手机号, [umoney] 余额 FROM [user_]"
        UpdateCommand="UPDATE user_ SET uname = @姓名, uloginname = @用户名, utel = @手机号, umoney = @余额 WHERE uid = @ID">
        <UpdateParameters>
            <asp:Parameter Name="ID" />
            <asp:Parameter Name="姓名" />
            <asp:Parameter Name="用户名" />
            <asp:Parameter Name="电话号" />
            <asp:Parameter Name="余额" />
        </UpdateParameters>
    </asp:SqlDataSource>


</asp:Content>
